---
codecov :
  notify:
    require_ci_to_pass: yes

ignore  :
- tests
- '*/tests/*'

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: yes
    patch:
      default:
        target: 80%
        threshold: 5%

    changes: no

parsers :
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment :
  layout: header, diff
  behavior: default
  require_changes: no
