// SPDX-FileCopyrightText: 2025 AlayaDB.AI
//
// SPDX-License-Identifier: AGPL-3.0-only
//
// AUTO-GENERATED by tools/codegen/gen.py. DO NOT EDIT.
// Source: tools/codegen/dispatch.yaml (33 combinations).
//
// This header contains the out-of-line definition of IndexFactory::create.
// It must be included from exactly ONE translation unit (python/src/index_factory.cpp)
// to avoid duplicate-symbol errors and to amortize the 33-template-specialization
// compile cost over a single .o file.
// Each migrated Gate 5 row names distinct current and legacy runtime types.
// The feature bit selects both the reported identity and the implementation.

#pragma once

#include "index.hpp"

namespace alaya {

auto IndexFactory::create(const IndexParams &params) -> std::unique_ptr<BasePyIndex> {
  return create(params, internal::memory::MemoryEngineFeatureFlags{});
}

auto IndexFactory::create(const IndexParams &params,
                          const internal::memory::MemoryEngineFeatureFlags &features)
    -> std::unique_ptr<BasePyIndex> {
  // float / uint32_t / NONE / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / NONE / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / NONE / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / SQ8 / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::SQ8
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
      using SearchSpaceType = SQ8Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = SQ8Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / SQ8 / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::SQ8
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
      using SearchSpaceType = SQ8Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = SQ8Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / SQ8 / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::SQ8
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
      using SearchSpaceType = SQ8Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = SQ8Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / SQ4 / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::SQ4
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
      using SearchSpaceType = SQ4Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = SQ4Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / SQ4 / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::SQ4
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
      using SearchSpaceType = SQ4Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = SQ4Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / SQ4 / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::SQ4
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
      using SearchSpaceType = SQ4Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint32_t,SequentialStorage<float,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = SQ4Space<float,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / RABITQ / HNSW
  // implementation=qg_segment engine=qg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::RABITQ
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "qg_segment", "qg"},
        {"hnsw", "legacy_qg_model", "qg"},
        internal::memory::EngineFeature::qg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RaBitQSpace<float,float,uint32_t,ScalarData>;
      using SearchSpaceType = RaBitQSpace<float,float,uint32_t,ScalarData>;
      using CurrentRuntimeType = QgSegment<SearchSpaceType>;
      using LegacyRuntimeType = HnswSegment<BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RaBitQSpace<float,float,uint32_t,EmptyScalarData>;
    using SearchSpaceType = RaBitQSpace<float,float,uint32_t,EmptyScalarData>;
    using CurrentRuntimeType = QgSegment<SearchSpaceType>;
    using LegacyRuntimeType = HnswSegment<BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / RABITQ / NSG
  // implementation=qg_segment engine=qg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::RABITQ
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "qg_segment", "qg"},
        {"nsg", "legacy_qg_model", "qg"},
        internal::memory::EngineFeature::qg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RaBitQSpace<float,float,uint32_t,ScalarData>;
      using SearchSpaceType = RaBitQSpace<float,float,uint32_t,ScalarData>;
      using CurrentRuntimeType = QgSegment<SearchSpaceType>;
      using LegacyRuntimeType = detail::NsgBuilderKernel<BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RaBitQSpace<float,float,uint32_t,EmptyScalarData>;
    using SearchSpaceType = RaBitQSpace<float,float,uint32_t,EmptyScalarData>;
    using CurrentRuntimeType = QgSegment<SearchSpaceType>;
    using LegacyRuntimeType = detail::NsgBuilderKernel<BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint32_t / RABITQ / FUSION
  // implementation=qg_segment engine=qg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::RABITQ
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "qg_segment", "qg"},
        {"fusion", "legacy_qg_model", "qg"},
        internal::memory::EngineFeature::qg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RaBitQSpace<float,float,uint32_t,ScalarData>;
      using SearchSpaceType = RaBitQSpace<float,float,uint32_t,ScalarData>;
      using CurrentRuntimeType = QgSegment<SearchSpaceType>;
      using LegacyRuntimeType = detail::FusionBuilderKernel<BuildSpaceType,detail::HnswBuilderKernel<BuildSpaceType>,detail::NsgBuilderKernel<BuildSpaceType>>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RaBitQSpace<float,float,uint32_t,EmptyScalarData>;
    using SearchSpaceType = RaBitQSpace<float,float,uint32_t,EmptyScalarData>;
    using CurrentRuntimeType = QgSegment<SearchSpaceType>;
    using LegacyRuntimeType = detail::FusionBuilderKernel<BuildSpaceType,detail::HnswBuilderKernel<BuildSpaceType>,detail::NsgBuilderKernel<BuildSpaceType>>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / NONE / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / NONE / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / NONE / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / SQ8 / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::SQ8
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
      using SearchSpaceType = SQ8Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = SQ8Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / SQ8 / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::SQ8
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
      using SearchSpaceType = SQ8Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = SQ8Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / SQ8 / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::SQ8
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
      using SearchSpaceType = SQ8Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = SQ8Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / SQ4 / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::SQ4
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
      using SearchSpaceType = SQ4Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = SQ4Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / SQ4 / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::SQ4
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
      using SearchSpaceType = SQ4Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = SQ4Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // float / uint64_t / SQ4 / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<float>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::SQ4
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
      using SearchSpaceType = SQ4Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<float,float,uint64_t,SequentialStorage<float,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = SQ4Space<float,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // int8_t / uint32_t / NONE / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<int8_t>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // int8_t / uint32_t / NONE / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<int8_t>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // int8_t / uint32_t / NONE / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<int8_t>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<int8_t,float,uint32_t,SequentialStorage<int8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // int8_t / uint64_t / NONE / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<int8_t>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // int8_t / uint64_t / NONE / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<int8_t>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // int8_t / uint64_t / NONE / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<int8_t>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<int8_t,float,uint64_t,SequentialStorage<int8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // uint8_t / uint32_t / NONE / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<uint8_t>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // uint8_t / uint32_t / NONE / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<uint8_t>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // uint8_t / uint32_t / NONE / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<uint8_t>())
      && params.id_type_.is(py::dtype::of<uint32_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using SearchSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<uint8_t,float,uint32_t,SequentialStorage<uint8_t,uint32_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // uint8_t / uint64_t / NONE / HNSW
  // implementation=hnsw_segment engine=hnsw
  if (params.data_type_.is(py::dtype::of<uint8_t>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::HNSW) {
    constexpr internal::memory::FactoryRegistration registration{
        {"hnsw", "hnsw_segment", "hnsw"},
        {"hnsw", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::none,
        true};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // uint8_t / uint64_t / NONE / NSG
  // implementation=nsg_segment engine=nsg
  if (params.data_type_.is(py::dtype::of<uint8_t>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::NSG) {
    constexpr internal::memory::FactoryRegistration registration{
        {"nsg", "nsg_segment", "nsg"},
        {"nsg", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::nsg_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = NsgSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  // uint8_t / uint64_t / NONE / FUSION
  // implementation=fusion_segment engine=fusion
  if (params.data_type_.is(py::dtype::of<uint8_t>())
      && params.id_type_.is(py::dtype::of<uint64_t>())
      && params.quantization_type_ == QuantizationType::NONE
      && params.index_type_ == IndexType::FUSION) {
    constexpr internal::memory::FactoryRegistration registration{
        {"fusion", "fusion_segment", "fusion"},
        {"fusion", "hnsw_segment", "hnsw"},
        internal::memory::EngineFeature::fusion_segment,
        false};
    if (params.has_scalar_data_) {
      using BuildSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using SearchSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,ScalarData>;
      using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
      using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
      if (registration.use_legacy(features)) {
        return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                            registration.legacy);
      }
      return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                           registration.current);
    }
    using BuildSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using SearchSpaceType = RawSpace<uint8_t,float,uint64_t,SequentialStorage<uint8_t,uint64_t>,EmptyScalarData>;
    using CurrentRuntimeType = FusionSegment<SearchSpaceType, BuildSpaceType>;
    using LegacyRuntimeType = HnswSegment<SearchSpaceType, BuildSpaceType>;
    if (registration.use_legacy(features)) {
      return std::make_unique<PyIndex<LegacyRuntimeType, SearchSpaceType>>(params,
                                                                          registration.legacy);
    }
    return std::make_unique<PyIndex<CurrentRuntimeType, SearchSpaceType>>(params,
                                                                         registration.current);
  }
  throw std::runtime_error(
      std::string("Unsupported dispatch combination: data_type=")
      + py::repr(params.data_type_).cast<std::string>()
      + ", id_type=" + py::repr(params.id_type_).cast<std::string>()
      + ", quantization_type=" + std::string(kQuantizationType2str[params.quantization_type_])
      + ", index_type=" + std::string(kIndexType2str[params.index_type_])
      + " (see tools/codegen/dispatch.yaml for supported combinations)");
}

}  // namespace alaya
