# SPDX-FileCopyrightText: 2026 AlayaDB.AI
# SPDX-License-Identifier: AGPL-3.0-only

"""Reviewed private stub for the canonical pybind11 module."""

from typing import ClassVar

import numpy as np
import numpy.typing as npt

_MetadataScalar = bool | int | float | str

__version__: str

class MetricType(metaclass=type):
    L2: ClassVar[MetricType]
    IP: ClassVar[MetricType]
    COS: ClassVar[MetricType]
    __members__: ClassVar[dict[str, MetricType]]
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

L2: MetricType
IP: MetricType
COS: MetricType

class CollectionStatusError(RuntimeError):
    status_code: int
    operation_stage: int
    status_detail: int
    retryability: int
    partial: bool
    status_version: str

class CollectionInvalidArgumentError(CollectionStatusError, ValueError): ...
class CollectionNotSupportedError(CollectionStatusError, NotImplementedError): ...
class CollectionConflictError(CollectionStatusError): ...
class CollectionNotFoundError(CollectionStatusError, KeyError): ...
class CollectionResourceExhaustedError(CollectionStatusError): ...
class CollectionDeadlineExceededError(CollectionStatusError): ...
class CollectionCancelledError(CollectionStatusError): ...
class CollectionIoError(CollectionStatusError): ...
class CollectionCorruptionError(CollectionStatusError): ...
class CollectionClosedError(CollectionStatusError): ...
class CollectionInternalError(CollectionStatusError): ...

class _RecordResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def id(self) -> str | int: ...
    @property
    def upsert_sequence(self) -> int: ...
    @property
    def document(self) -> str: ...
    @property
    def metadata(self) -> dict[str, _MetadataScalar]: ...
    @property
    def vector(self) -> npt.NDArray[np.generic] | None: ...

class _MutationRowResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def op_id(self) -> int: ...
    @property
    def batch_op_id(self) -> int: ...
    @property
    def row_op_id(self) -> int: ...
    @property
    def visibility_watermark(self) -> int: ...
    @property
    def durable_watermark(self) -> int: ...
    @property
    def searchable(self) -> bool: ...
    @property
    def durability(self) -> int: ...
    @property
    def row_status(self) -> int: ...
    @property
    def retry_token(self) -> str: ...

class _MutationResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def batch_op_id(self) -> int: ...
    @property
    def visibility_watermark(self) -> int: ...
    @property
    def durable_watermark(self) -> int: ...
    @property
    def searchable(self) -> bool: ...
    @property
    def durability(self) -> int: ...
    @property
    def retry_token(self) -> str: ...
    @property
    def rows(self) -> list[_MutationRowResponse]: ...

class _SearchStatsResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def filter_active(self) -> bool: ...
    @property
    def filter_execution(self) -> str: ...
    @property
    def filter_examined(self) -> int: ...
    @property
    def filter_passed(self) -> int: ...
    @property
    def nan_discarded(self) -> int: ...
    @property
    def overfetch_rounds(self) -> int: ...
    @property
    def budget_consumed(self) -> int: ...
    @property
    def lease_acquired(self) -> int: ...
    @property
    def lease_released(self) -> int: ...
    @property
    def lease_peak_bytes(self) -> int: ...
    @property
    def io_requests_consumed(self) -> int: ...
    @property
    def io_bytes_consumed(self) -> int: ...
    @property
    def rerank_nanoseconds(self) -> int: ...
    @property
    def effective_effort(self) -> int | None: ...

class _SearchResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def ids(self) -> npt.NDArray[np.object_]: ...
    @property
    def distances(self) -> npt.NDArray[np.float32]: ...
    @property
    def offsets(self) -> npt.NDArray[np.uint64]: ...
    @property
    def valid_counts(self) -> npt.NDArray[np.uint64]: ...
    @property
    def status_codes(self) -> npt.NDArray[np.uint8]: ...
    @property
    def completeness_codes(self) -> npt.NDArray[np.uint8]: ...
    @property
    def visibility_watermark(self) -> int: ...
    @property
    def metadata_epoch(self) -> int: ...
    @property
    def search_stats(self) -> _SearchStatsResponse: ...

class _CheckpointResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def durable_watermark(self) -> int: ...
    @property
    def wal_cut(self) -> int: ...
    @property
    def metadata_epoch(self) -> int: ...
    @property
    def checkpoint_name(self) -> str: ...

class _SealResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def source_segment_id(self) -> int: ...
    @property
    def successor_segment_id(self) -> int: ...
    @property
    def sealed_segment_id(self) -> int: ...
    @property
    def wal_cut(self) -> int: ...
    @property
    def sealed_rows(self) -> int: ...
    @property
    def sealed_bytes(self) -> int: ...
    @property
    def manifest_generation(self) -> int: ...

class _CompactResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def source_segment_ids(self) -> list[int]: ...
    @property
    def compacted_segment_id(self) -> int: ...
    @property
    def compacted_rows(self) -> int: ...
    @property
    def input_bytes(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def manifest_generation(self) -> int: ...

class _GcResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def pending(self) -> int: ...
    @property
    def reclaimed(self) -> int: ...
    @property
    def deferred(self) -> int: ...
    @property
    def reclaimed_bytes(self) -> int: ...
    @property
    def manifest_generation(self) -> int: ...

class _StatsResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def accepted_count(self) -> int: ...
    @property
    def pending_count(self) -> int: ...
    @property
    def searchable_bytes(self) -> int: ...
    @property
    def accepted_bytes(self) -> int: ...
    @property
    def searchable_vector_bytes(self) -> int: ...
    @property
    def accepted_vector_bytes(self) -> int: ...
    @property
    def pending_bytes(self) -> int: ...
    @property
    def allocated_count(self) -> int: ...
    @property
    def tombstone_count(self) -> int: ...
    @property
    def routing_generation(self) -> int: ...
    @property
    def visibility_watermark(self) -> int: ...
    @property
    def durable_watermark(self) -> int: ...
    @property
    def metadata_epoch(self) -> int: ...
    @property
    def sealed_segments_count(self) -> int: ...
    @property
    def gc_pending_count(self) -> int: ...
    @property
    def active_segment_algorithm(self) -> str: ...
    @property
    def compacted_bytes(self) -> int: ...
    @property
    def lifecycle(self) -> int: ...

class _OptionsResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def root(self) -> str: ...
    @property
    def read_only(self) -> bool: ...
    @property
    def dim(self) -> int: ...
    @property
    def metric(self) -> str: ...
    @property
    def dtype(self) -> np.dtype[np.generic]: ...
    @property
    def index_type(self) -> str: ...
    @property
    def quantization_type(self) -> str: ...
    @property
    def build_threads(self) -> int: ...
    @property
    def max_neighbors(self) -> int: ...
    @property
    def ef_construction(self) -> int: ...
    @property
    def implementation_key(self) -> str: ...
    @property
    def engine_factory_key(self) -> str: ...
    @property
    def active_algorithm(self) -> str: ...
    @property
    def auto_seal_rows(self) -> int: ...

class _CapabilitiesResponse(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def index_types(self) -> list[str]: ...
    @property
    def laser_enabled(self) -> bool: ...
    @property
    def laser_simd(self) -> str | None: ...

def capabilities() -> _CapabilitiesResponse: ...

class _Collection(metaclass=type):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @staticmethod
    def create(
        root: str,
        dim: int,
        metric: str,
        dtype: np.dtype[np.generic],
        index_type: str,
        quantization_type: str,
        build_threads: int = ...,
        max_neighbors: int = ...,
        ef_construction: int = ...,
        auto_seal_rows: int = ...,
    ) -> _Collection: ...
    @staticmethod
    def open(root: str, read_only: bool = ...) -> _Collection: ...
    def mutate(
        self,
        ids: list[str],
        documents: list[str],
        vectors: npt.NDArray[np.generic],
        metadata: list[dict[str, _MetadataScalar] | None],
        action: str,
        *,
        mode: str = ...,
        durability: str = ...,
        retry_token: str = ...,
    ) -> _MutationResponse: ...
    def remove(
        self,
        ids: list[str],
        *,
        mode: str = ...,
        durability: str = ...,
        retry_token: str = ...,
    ) -> _MutationResponse: ...
    def search(
        self,
        query: npt.NDArray[np.generic],
        top_k: int,
        *,
        effort: int = ...,
        metadata_filter: dict[str, object] | None = ...,
        filter_policy: str = ...,
        filter_selectivity: float | None = ...,
        scratch_budget_bytes: int = ...,
        io_budget_requests: int = ...,
        io_budget_bytes: int = ...,
    ) -> _SearchResponse: ...
    def batch_search(
        self,
        queries: npt.NDArray[np.generic],
        top_k: int,
        *,
        effort: int = ...,
        metadata_filter: dict[str, object] | None = ...,
        filter_policy: str = ...,
        filter_selectivity: float | None = ...,
        scratch_budget_bytes: int = ...,
        io_budget_requests: int = ...,
        io_budget_bytes: int = ...,
    ) -> _SearchResponse: ...
    def get_by_id(self, id: str, *, include_vector: bool = ...) -> _RecordResponse | None: ...
    def get_by_ids(self, ids: list[str], *, include_vector: bool = ...) -> list[_RecordResponse | None]: ...
    def records(self) -> list[_RecordResponse]: ...
    def scan(
        self,
        *,
        metadata_filter: dict[str, object] | None = ...,
        limit: int = ...,
        include_vector: bool = ...,
    ) -> list[_RecordResponse]: ...
    def checkpoint(self) -> _CheckpointResponse: ...
    def seal(self) -> _SealResponse: ...
    def compact(self) -> _CompactResponse: ...
    def gc(self) -> _GcResponse: ...
    def stats(self) -> _StatsResponse: ...
    def options(self) -> _OptionsResponse: ...
    def close(self) -> None: ...
