# Print build configuration summary Usage: print_build_summary()
function(print_build_summary)
  message(STATUS "")
  message(STATUS "+===========================================================+")
  message(STATUS "|                  ${PROJECT_NAME} Build Configuration")
  message(STATUS "+===========================================================+")
  message(STATUS "| Platform:")
  message(STATUS "|   - OS              : ${CMAKE_SYSTEM_NAME}")
  message(STATUS "|   - Architecture    : ${CMAKE_SYSTEM_PROCESSOR}")
  message(STATUS "|")
  message(STATUS "| Build Information:")
  message(STATUS "|   - Build Type      : ${CMAKE_BUILD_TYPE}")
  message(STATUS "|   - C++ Standard    : C++${CMAKE_CXX_STANDARD}")
  message(STATUS "|   - Compiler        : ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "|   - CMake Version   : ${CMAKE_VERSION}")
  message(STATUS "|")
  message(STATUS "| Compiler Flags:")
  get_directory_property(_compile_opts COMPILE_OPTIONS)
  message(STATUS "|   - Compile Options : ${_compile_opts}")
  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    message(STATUS "|   - Release Flags   : ${CMAKE_CXX_FLAGS_RELEASE}")
  elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "|   - Debug Flags     : ${CMAKE_CXX_FLAGS_DEBUG}")
  endif()
  message(STATUS "|")
  message(STATUS "| Dependencies:")
  if(TARGET OpenMP::OpenMP_CXX)
    message(STATUS "|   - OpenMP          : ${OpenMP_CXX_VERSION}")
  endif()
  if(Eigen3_FOUND)
    message(STATUS "|   - Eigen3          : ${Eigen3_VERSION}")
  endif()
  if(spdlog_FOUND)
    message(STATUS "|   - spdlog          : ${spdlog_VERSION}")
  endif()
  if(pybind11_FOUND)
    message(STATUS "|   - pybind11        : ${pybind11_VERSION}")
    message(STATUS "|   - Python          : ${Python_VERSION}")
  endif()
  message(STATUS "|")
  message(STATUS "| Project Options:")
  message(STATUS "|   - BUILD_TESTING   : ${BUILD_TESTING}")
  message(STATUS "|   - ENABLE_COVERAGE : ${ENABLE_COVERAGE}")
  message(STATUS "+===========================================================+")
  message(STATUS "")
endfunction()
