# SPDX-FileCopyrightText: 2025 AlayaDB.AI
#
# SPDX-License-Identifier: AGPL-3.0-only

# PrintSummary.cmake - the configuration banner printed at the end of every configure.

include_guard(GLOBAL)

function(print_dependency_summary)
  message(STATUS "| Dependencies:")
  if(TARGET OpenMP::OpenMP_CXX)
    message(STATUS "|   - OpenMP          : ${OpenMP_CXX_VERSION}")
  else()
    message(STATUS "|   - OpenMP          : unavailable (serial fallback)")
  endif()
  if(Eigen3_FOUND)
    message(STATUS "|   - Eigen3          : ${Eigen3_VERSION}")
  endif()
  if(spdlog_FOUND)
    message(STATUS "|   - spdlog          : ${spdlog_VERSION}")
  endif()
  if(RocksDB_FOUND)
    message(STATUS "|   - RocksDB         : ${RocksDB_VERSION}")
  endif()
  if(liburing_FOUND)
    message(STATUS "|   - liburing        : ${liburing_VERSION}")
  endif()
  if(pybind11_FOUND)
    message(STATUS "|   - pybind11        : ${pybind11_VERSION}")
  endif()
  if(Python_FOUND)
    message(STATUS "|   - Python          : ${Python_VERSION} (${Python_EXECUTABLE})")
  endif()
endfunction()

function(print_project_options_summary)
  message(STATUS "|")
  message(STATUS "| Project Options:")
  message(STATUS "|   - BUILD_PYTHON    : ${BUILD_PYTHON}")
  message(STATUS "|   - BUILD_TESTING   : ${BUILD_TESTING}")
  message(STATUS "|   - ENABLE_COVERAGE : ${ENABLE_COVERAGE}")
  message(STATUS "|   - NATIVE_ARCH     : ${ALAYA_NATIVE_ARCH}")
  message(STATUS "|   - ENABLE_LASER    : ${ALAYA_ENABLE_LASER}")
endfunction()

# Print build configuration summary Usage: print_build_summary()
function(print_build_summary)
  message(STATUS "")
  message(STATUS "+===========================================================+")
  message(STATUS "|                  ${PROJECT_NAME} Build Configuration")
  message(STATUS "+===========================================================+")
  message(STATUS "| Platform:")
  message(STATUS "|   - OS              : ${CMAKE_SYSTEM_NAME}")
  message(STATUS "|   - Architecture    : ${CMAKE_SYSTEM_PROCESSOR}")
  message(STATUS "|")
  message(STATUS "| Build Information:")
  message(STATUS "|   - Build Type      : ${CMAKE_BUILD_TYPE}")
  message(STATUS "|   - C++ Standard    : C++${CMAKE_CXX_STANDARD}")
  message(STATUS "|   - Compiler        : ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "|   - CMake Version   : ${CMAKE_VERSION}")
  message(STATUS "|")
  message(STATUS "| Compiler Flags:")
  if(TARGET alaya_build_flags)
    get_target_property(_compile_opts alaya_build_flags INTERFACE_COMPILE_OPTIONS)
    message(STATUS "|   - Compile Options : ${_compile_opts}")
  endif()
  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    message(STATUS "|   - Release Flags   : ${CMAKE_CXX_FLAGS_RELEASE}")
  elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "|   - Debug Flags     : ${CMAKE_CXX_FLAGS_DEBUG}")
  endif()
  message(STATUS "|")
  print_dependency_summary()
  print_project_options_summary()
  message(STATUS "+===========================================================+")
  message(STATUS "")
endfunction()
