# SPDX-FileCopyrightText: 2025 AlayaDB.AI
#
# SPDX-License-Identifier: AGPL-3.0-only

# AUTO-GENERATED by tools/codegen/gen.py. DO NOT EDIT.
# Source: tools/codegen/dispatch.yaml (11 combinations).

"""Generated dispatch matrix parameters used by test_dispatch_matrix."""

import numpy as np

_FULL_PARAMS = [
    (np.float32, np.uint32, "none", "hnsw", False),
    (np.float32, np.uint32, "sq8", "hnsw", False),
    (np.float32, np.uint32, "sq4", "hnsw", False),
    (np.float32, np.uint32, "rabitq", "hnsw", False),
    (np.float32, np.uint64, "none", "hnsw", False),
    (np.float32, np.uint64, "sq8", "hnsw", False),
    (np.float32, np.uint64, "sq4", "hnsw", False),
    (np.int8, np.uint32, "none", "hnsw", False),
    (np.int8, np.uint64, "none", "hnsw", False),
    (np.uint8, np.uint32, "none", "hnsw", False),
    (np.uint8, np.uint64, "none", "hnsw", False),
]

# Positional peer of _FULL_PARAMS.  Keeping identity metadata separate avoids
# changing the long-standing five-field construction matrix tuple.
_IMPLEMENTATION_IDENTITIES = [
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("qg_segment", "qg", "qg"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
    ("hnsw_segment", "hnsw", "hnsw"),
]
